return {
	{
		'pwntester/octo.nvim',
		dependencies = {
			'nvim-lua/plenary.nvim',
			'nvim-tree/nvim-web-devicons',
			'folke/snacks.nvim',
		},
		cmd = 'Octo',
		opts = {
			picker = 'snacks',
			enable_builtin = true,
			default_remote = { 'upstream', 'origin' },
			ssh_aliases = {},
			comment_icon = '▎',
			outdated_icon = '󰅒 ',
			resolved_icon = ' ',
			reaction_viewer_hint_icon = ' ',
			user_icon = ' ',
			timeline_marker = ' ',
			timeline_indent = '2',
			right_bubble_delimiter = '',
			left_bubble_delimiter = '',
			github_hostname = '',
			file_panel = {
				size = 10,
				use_icons = true,
			},
			mappings = {
				issue = {
					close_issue = { lhs = '<leader>ic', desc = 'close issue' },
					reopen_issue = { lhs = '<leader>io', desc = 'reopen issue' },
					list_issues = { lhs = '<leader>il', desc = 'list open issues on same repo' },
					reload = { lhs = '<C-r>', desc = 'reload issue' },
					open_in_browser = { lhs = '<C-b>', desc = 'open issue in browser' },
					copy_url = { lhs = '<C-y>', desc = 'copy URL to system clipboard' },
					add_assignee = { lhs = '<leader>aa', desc = 'add assignee' },
					remove_assignee = { lhs = '<leader>ad', desc = 'remove assignee' },
					add_label = { lhs = '<leader>la', desc = 'add label' },
					remove_label = { lhs = '<leader>ld', desc = 'remove label' },
					add_comment = { lhs = '<leader>ca', desc = 'add comment' },
					delete_comment = { lhs = '<leader>cd', desc = 'delete comment' },
					react_hooray = { lhs = '<leader>rh', desc = 'add/remove 🎉 reaction' },
					react_heart = { lhs = '<leader>rH', desc = 'add/remove ❤️ reaction' },
					react_eyes = { lhs = '<leader>re', desc = 'add/remove 👀 reaction' },
					react_thumbs_up = { lhs = '<leader>r+', desc = 'add/remove 👍 reaction' },
					react_thumbs_down = { lhs = '<leader>r-', desc = 'add/remove 👎 reaction' },
					react_rocket = { lhs = '<leader>rr', desc = 'add/remove 🚀 reaction' },
					react_laugh = { lhs = '<leader>rl', desc = 'add/remove 😄 reaction' },
					react_confused = { lhs = '<leader>rc', desc = 'add/remove 😕 reaction' },
				},
				pull_request = {
					checkout_pr = { lhs = '<leader>po', desc = 'checkout PR' },
					merge_pr = { lhs = '<leader>pm', desc = 'merge commit PR' },
					squash_and_merge_pr = { lhs = '<leader>psm', desc = 'squash and merge PR' },
					rebase_and_merge_pr = { lhs = '<leader>prm', desc = 'rebase and merge PR' },
					list_commits = { lhs = '<leader>pc', desc = 'list PR commits' },
					list_changed_files = { lhs = '<leader>pf', desc = 'list PR changed files' },
					show_pr_diff = { lhs = '<leader>pd', desc = 'show PR diff' },
					add_reviewer = { lhs = '<leader>va', desc = 'add reviewer' },
					remove_reviewer = { lhs = '<leader>vd', desc = 'remove reviewer' },
					close_pr = { lhs = '<leader>ic', desc = 'close PR' },
					reopen_pr = { lhs = '<leader>io', desc = 'reopen PR' },
					reload = { lhs = '<C-r>', desc = 'reload PR' },
					open_in_browser = { lhs = '<C-b>', desc = 'open PR in browser' },
					copy_url = { lhs = '<C-y>', desc = 'copy URL to system clipboard' },
					add_assignee = { lhs = '<leader>aa', desc = 'add assignee' },
					remove_assignee = { lhs = '<leader>ad', desc = 'remove assignee' },
					add_label = { lhs = '<leader>la', desc = 'add label' },
					remove_label = { lhs = '<leader>ld', desc = 'remove label' },
					add_comment = { lhs = '<leader>ca', desc = 'add comment' },
					delete_comment = { lhs = '<leader>cd', desc = 'delete comment' },
					react_hooray = { lhs = '<leader>rh', desc = 'add/remove 🎉 reaction' },
					react_heart = { lhs = '<leader>rH', desc = 'add/remove ❤️ reaction' },
					react_eyes = { lhs = '<leader>re', desc = 'add/remove 👀 reaction' },
					react_thumbs_up = { lhs = '<leader>r+', desc = 'add/remove 👍 reaction' },
					react_thumbs_down = { lhs = '<leader>r-', desc = 'add/remove 👎 reaction' },
					react_rocket = { lhs = '<leader>rr', desc = 'add/remove 🚀 reaction' },
					react_laugh = { lhs = '<leader>rl', desc = 'add/remove 😄 reaction' },
					react_confused = { lhs = '<leader>rc', desc = 'add/remove 😕 reaction' },
					review_start = { lhs = '<leader>vs', desc = 'start a review' },
					review_resume = { lhs = '<leader>vr', desc = 'resume a review' },
				},
				review_thread = {
					add_comment = { lhs = '<leader>ca', desc = 'add comment' },
					add_suggestion = { lhs = '<leader>sa', desc = 'add suggestion' },
					delete_comment = { lhs = '<leader>cd', desc = 'delete comment' },
					submit_review = { lhs = '<leader>vs', desc = 'submit review' },
					resolve_thread = { lhs = '<leader>vr', desc = 'resolve thread' },
					unresolve_thread = { lhs = '<leader>vu', desc = 'unresolve thread' },
				},
				submit_win = {
					approve_review = { lhs = '<C-a>', desc = 'approve review' },
					comment_review = { lhs = '<C-m>', desc = 'comment review' },
					request_changes = { lhs = '<C-r>', desc = 'request changes' },
					close_review_tab = { lhs = '<C-c>', desc = 'close review tab' },
				},
				file_panel = {
					next_entry = { lhs = 'j', desc = 'move to next changed file' },
					prev_entry = { lhs = 'k', desc = 'move to previous changed file' },
					select_entry = { lhs = '<cr>', desc = 'show selected changed file diffs' },
					refresh_files = { lhs = 'R', desc = 'refresh changed files panel' },
					toggle_viewed = { lhs = '<leader>e', desc = 'toggle file viewed state' },
					goto_file = { lhs = 'gf', desc = 'go to file' },
				},
			},
		},
		keys = {
			{ '<leader>opl', '<cmd>Octo pr list<cr>',     desc = 'Octo: list PRs' },
			{ '<leader>ops', '<cmd>Octo pr search<cr>',   desc = 'Octo: search PRs' },
			{ '<leader>opc', '<cmd>Octo pr create<cr>',   desc = 'Octo: create PR' },
			{ '<leader>oil', '<cmd>Octo issue list<cr>',   desc = 'Octo: list issues' },
			{ '<leader>oic', '<cmd>Octo issue create<cr>', desc = 'Octo: create issue' },
			{ '<leader>ois', '<cmd>Octo issue search<cr>', desc = 'Octo: search issues' },
		},
	},
}
